apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pko5m6jfm-go 
  janus-idp.io/tekton: pko5m6jfm-go
  backstage.io/kubernetes-id: pko5m6jfm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pko5m6jfm-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  